---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: _pages
  label: _pages
  create: all
  match: "**/*"
- type: directory
  path: _elo
  label: Elo
  create: all
  match: "**/*"
- type: directory
  path: _interclubs
  label: Interclubs
  create: all
  match: "**/*"
- type: directory
  path: _inzet
  label: Inzet
  create: all
  match: "**/*"
- type: directory
  path: _klubkampioenschap
  label: Klubkampioenschap
  create: all
  match: "**/*"
- type: directory
  path: _memorial
  label: Memorial
  create: all
  match: "**/*"
- type: directory
  path: _open
  label: Open
  create: all
  match: "**/*"
- type: directory
  path: _snelschaak
  label: Snelschaak
  create: all
  match: "**/*"
- type: jekyll-posts
  label: Posts
  create: all
- type: jekyll-pages
  label: Pages
  create: all
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
